import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>typeworks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section></section>
      </main>

      <footer>
        Powered by{' '}
        <a
          href="#https://github.com/sebastianbaechler"
          target="_blank"
          rel="noopener noreferrer"
        >
          Sebastian Baechler
        </a>
      </footer>
    </>
  );
};

export default Home;
